services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    volumes:
      - /sys:/sys:ro
      - /proc:/proc:ro
    environment:
      - SSH_USER=${SSH_USER}
      - SSH_HOST=${SSH_HOST}
      - SSH_PASSWORD=${SSH_PASSWORD}
      - docker_mode=true
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host # needed for that ssh shit i wrote to execute command from container to host
