version: "3.9"

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    volumes:
      - /sys:/sys:ro
      - /proc:/proc:ro
    tty: true
    stdin_open: true
    privileged: true   # only if you really need host-like shell access
    network_mode: host
